version: '2'
services:
  jenkins:
    container_name: jenkins
    image: '{{image_name}}:{{tag}}'
    ports:
      - '{{port}}:8080'
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      CASC_JENKINS_CONFIG: /tmp
    volumes:
      - {{project_dir}}/casc.yaml:/tmp/casc.yml